#!/bin/sh
#
# Starts ui_app
#

start() {
    /usr/bin/ui_app &
}

stop() {
    killall ui_app
}

restart() {
	stop
	start
}

case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?