#!/bin/sh
#
# Starts web_server
#

start() {
    /usr/bin/web_server &
}

stop() {
    killall web_server
}

restart() {
	stop
	start
}

case "$1" in
  start|stop|restart)
	"$1"
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?